runtime: python
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"

entrypoint: streamlit run main.py --server.port $PORT

instance_class: F2

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2